apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: extension-projects
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
  - web:
      url: https://github.com/sisu-tech/project-env-extension/releases/download/v0.0.1/extension.tar
